# -*- coding: utf-8 -*-
"""Python Session.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12jLPTBNVmSv3ThF5wxxFZE9CDa7Kdb3R
"""

# .py( Python File ) - # .ipynb - python Notebook

print("Hello World")
# print() -- Function
# Inbuilt Function & User Defined Function

# Inbuilt Function
# Whose Functionlity is Already Present in Python
# Parameter & Output

# Microwave
# Raw Material => Inside Microwave => Cooked Food
# Cold Food => M => Hot Food

# Inbuilt Function
# Parameter
# Output

# Print()
print("Anshika")
# Multiple Parameter
print("Anshika Y","Anshika E","Anshika S") # N PARAMETERS

# Python Code
# Multiple Lines

# Runs Line by Line
# Capital Letter, Small Letter, Capital/Small
# Not case sensitive
name = "Abhishek"
# name - variable
# Variable name can be anything

# Data Types
# String, Integer, Float
# String - alphabetical value, alphanumeric value, '123'
# Integer - -123, 123, 345
# Float - 121.67, 1.001

name = 'Anshika Singh'
type(name)

number = '123'
print(type(number))

# When you have some values (with which you have to do calculations) - Int, Float
# Mobile Number (str)

7*8
5*6
4+3
5-5

7*8 # 56 # No
print(5*6) # 30 will 100% come
4+3 # 7 # No
5-5 # 0 # Yes

# Input in Python
# marks of 3 students
student1 = 5 # static code
student2 = 7 # static code
student3 = 9 # code
print(student1+student2+student3)

# App - Calculator - Logic (Code) - # Different Number (Differnet Marks)

a = input('Enter your number ') # String
print(type(a))

a = int(input('Enter your number ')) # String to Integer (Type Casting)
print(type(a))

a = int(input('Enter a '))
b = int(input('Enter b '))
print(a+b)

a = 'Bangalore is a great City'
a.split()

a = 'Bangalore,is,a great,City'
a.split(',')

maths, physics, chemistry = map( int, input().split())
print(maths+physics+chemistry)
# '45 67 89'
# '60 78 89' => '60', '78', '89' => 60, 78, 89

name1, name2, name3 = input().split()
print(name1,name2,name3)
# '45 67 89'

# Operators
1+1
1*1
1-1
1/1 # 1 # int / int => float
4//5 # 0.8 # value which is left side of decimal (Floor value)
4**5 # 4 to the power 5

# comparison operators
a=5 # I am assigning a value 5 to a (=Assignment operator)
a==6 # == MEANS COMPARISON

# Conditional Statements

maths_marks = int(input('Enter Maths Marks '))
if maths_marks >= 90:
  print('Give him/her a laptop')
elif maths_marks == 80:
  print('Give him/her a mobile phone')
elif maths_marks == 70:
  print('Give him/her a chocolate')
elif maths_marks == 60:
  print('Give him/her a pen')
else:
  print('No Prize')

import pandas as pd
import io

df = pd.read_csv('/content/Road Accident Data.xlsx - Sheet1.csv')

df.head()